//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVCProject_NguyenVuongThienPhuc
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movie()
        {
            this.schedules = new HashSet<schedule>();
        }

        [Key]
        [ReadOnly(true)]
        public int movieID { get; set; }

        [Required]
        [Display(Name = "Movie Name")]
        public string movieName { get; set; }
        public int categoryID { get; set; }

        [Required]
        [Display(Name = "Release Date")]
        [DataType(DataType.Date)]
        public System.DateTime publishDate { get; set; }

        [Required]
        [Display(Name = "Ticket Price")]
        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "${0}", ApplyFormatInEditMode = false)]
        public decimal price { get; set; }

        [Required]
        [Display(Name = "Trailer")]
        [DataType(DataType.Html)]
        public string trailerEmbedHTML { get; set; }

        [Required]
        [Display(Name = "Length")]
        [DisplayFormat(DataFormatString = "{0} minutes", ApplyFormatInEditMode = false)]
        public int length { get; set; }

        [Required]
        [Display(Name = "Image")]
        [DataType(DataType.ImageUrl)]
        public string imageLink { get; set; }

        [Required]
        [Display(Name = "Introduction")]
        public string description { get; set; }

        [Required]
        [Display(Name = "Rated")]
        public int ratedID { get; set; }
        public string language { get; set; }
        public string url { get; set; }

        public virtual category category { get; set; }
        public virtual movieRated movieRated { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<schedule> schedules { get; set; }
    }
}
