//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVCProject_NguyenVuongThienPhuc
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_items
    {
        public int orderID { get; set; }
        public string ticketID { get; set; }
        public int seatID { get; set; }
        public bool isAdult { get; set; }
        public Nullable<int> foodID { get; set; }
        public int discount { get; set; }
    
        public virtual snack snack { get; set; }
        public virtual order order { get; set; }
    }
}
